actions:
  metadata:
    name: ibmcloudEnablement
    description: "Installation for IBM Cloud"
  actionDefs:
    preInstall:
      metadata:
        name: preInstall
        description: "Prerequisites to installing Cloud Pak for Applications"
      roles:
      - clusterAdmin
      requires:
        "/case/prereqs/k8sDistros/ibmCloud"
      k8sPermissions:
        rules:
        - rule:
            group: "*"
            resource: "*"
            verbs:
            - "*"

    install:
      metadata:
        name: install
        description: "Install the IBM Cloud Pak for Applications"
      roles:
      - namespaceAdmin
      requires:
        "/case/prereqs/k8sDistros/ibmCloud"
      k8sPermissions:
        rules:
        - rule:
            group: "*"
            resource: "*"
            verbs:
            - "*"
